-- rerun
BEGIN;

DROP TABLE IF EXISTS spaces        CASCADE;
DROP TABLE IF EXISTS pricing       CASCADE;
DROP TABLE IF EXISTS working_hours CASCADE;
DROP TABLE IF EXISTS reservations  CASCADE;

-- spaces
CREATE TABLE IF NOT EXISTS spaces (
    level             VARCHAR(3)  NOT NULL,
    space_type        VARCHAR(20) NOT NULL CHECK (space_type IN ('STANDARD','OVERSIZED', 'EV')),
    amount            INT         NOT NULL,
    UNIQUE (level, space_type)
);
COMMENT ON COLUMN spaces.level IS 'Parking spacel level';
COMMENT ON COLUMN spaces.space_type IS 'Parking level space type';
COMMENT ON COLUMN spaces.amount IS 'Amount of privided space type at level';

-- pricing
CREATE TABLE pricing (
    price_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_type     TEXT,
    amount         NUMERIC(8,2) NOT NULL CHECK (amount >= 0),
    currency       CHAR(3) NOT NULL DEFAULT 'EUR',
    description    TEXT 
);
COMMENT ON COLUMN pricing.price_id IS 'Surrogate primary key for the price record';
COMMENT ON COLUMN pricing.price_type IS 'space_types; space type this price applies to';
COMMENT ON COLUMN pricing.amount IS 'Price charged per hour, in `currency`';
COMMENT ON COLUMN pricing.currency IS 'ISO-4217 currency code for the rates';


-- working_hours
CREATE TABLE working_hours (
    hours_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week     TEXT,
    opens_at        TIME,
    closes_at       TIME,
    is_24h          BOOLEAN  NOT NULL DEFAULT FALSE,
    is_closed       BOOLEAN  NOT NULL DEFAULT FALSE,
    CONSTRAINT unique_working_hours UNIQUE (day_of_week),
    CONSTRAINT check_hours_not_both CHECK (NOT (is_24h AND is_closed)),
    CONSTRAINT check_hours_times CHECK (
        (is_24h OR is_closed) AND opens_at IS NULL AND closes_at IS NULL
        OR
        (NOT is_24h AND NOT is_closed AND opens_at IS NOT NULL AND closes_at IS NOT NULL)
    )
);
COMMENT ON COLUMN working_hours.hours_id IS 'Surrogate primary key for the hours row';
COMMENT ON COLUMN working_hours.day_of_week IS 'ISO-8601 weekday: 1=Monday ... 7=Sunday';
COMMENT ON COLUMN working_hours.opens_at IS 'Opening time; NULL when is_24h or is_closed';
COMMENT ON COLUMN working_hours.closes_at IS 'Closing time; NULL when is_24h or is_closed';
COMMENT ON COLUMN working_hours.is_24h IS 'TRUE if open around the clock on this day';
COMMENT ON COLUMN working_hours.is_closed IS 'TRUE if fully closed on this day';


CREATE OR REPLACE VIEW vw_working_hours
AS
SELECT  wh.hours_id,
        wh.day_of_week, 
        CASE 
            WHEN wh.is_closed then null
            WHEN wh.is_24h THEN '00:00'
            ELSE wh.opens_at
        END as opens_at,
        CASE 
            WHEN wh.is_closed then null
            WHEN wh.is_24h THEN '23:59'
            ELSE wh.closes_at
        END as closes_at,
        wh.is_closed as temporaly_closed
FROM  working_hours wh
ORDER BY wh.day_of_week;


-- SEED DATA
-- pricing
INSERT INTO pricing (price_type, amount, currency, description) VALUES
    ('hourly',      3.00, 'EUR', 'Standard hourly rate for all space types'),
    ('daily_max',  25.00, 'EUR', 'Maximum charge per calendar day'),
    ('monthly',   200.00, 'EUR', 'Monthly subscription — unlimited in/out access'),
    ('ev_charging', 0.30, 'EUR', 'EV charging rate per kWh')
;


-- working_hours
INSERT INTO working_hours (day_of_week, opens_at, closes_at) VALUES
    ('Monday',    '05:00', '23:59'),
    ('Tuesday',   '05:00', '23:59'),
    ('Thursday',  '05:00', '23:59'),
    ('Friday',    '05:00', '23:59')
;
INSERT INTO working_hours (day_of_week, is_closed) VALUES
    ('Wednesday', TRUE)
;
INSERT INTO working_hours (day_of_week, is_24h) VALUES
    ('Saturday',  TRUE),
    ('Sunday',    TRUE)
;

-- spaces
INSERT INTO spaces (level, amount, space_type) VALUES 
    ('B1', 100, 'STANDARD'), ('B1', 30, 'EV'), ('B1', 10, 'OVERSIZED'),
    ('B2', 100, 'STANDARD'), ('B2', 35, 'EV'), ('B2', 5, 'OVERSIZED'),
    ('B3', 100, 'STANDARD'), ('B3', 25, 'EV'), ('B3', 15, 'OVERSIZED')
;

COMMIT;
