-- rerun
BEGIN;

DROP TABLE IF EXISTS spaces  CASCADE;
DROP TABLE IF EXISTS pricing         CASCADE;
DROP TABLE IF EXISTS working_hours   CASCADE;
DROP TABLE IF EXISTS reservations    CASCADE;

-- spaces
CREATE TABLE IF NOT EXISTS spaces (
    space_id     SERIAL PRIMARY KEY,
    level        VARCHAR(10)  NOT NULL,
    space_number VARCHAR(10)  NOT NULL,
    space_type   VARCHAR(20)  NOT NULL CHECK (space_type IN ('STANDARD', 'COMPACT', 'OVERSIZED', 'EV', 'ACCESSIBLE')),
    status       VARCHAR(20)  NOT NULL DEFAULT 'operating' CHECK (status IN ('operating', 'maintenance')),
    UNIQUE (level, space_number)
);

-- pricing
CREATE TABLE pricing (
    price_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_type     TEXT,
    amount         NUMERIC(8,2) NOT NULL CHECK (amount >= 0),
    currency       CHAR(3) NOT NULL DEFAULT 'EUR',
    description    TEXT 
);
COMMENT ON COLUMN pricing.price_id IS 'Surrogate primary key for the price record';
COMMENT ON COLUMN pricing.price_type IS 'space_types; space type this price applies to';
COMMENT ON COLUMN pricing.amount IS 'Price charged per hour, in `currency`';
COMMENT ON COLUMN pricing.currency IS 'ISO-4217 currency code for the rates';


-- working_hours
CREATE TABLE working_hours (
    hours_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week     TEXT,
    opens_at        TIME,
    closes_at       TIME,
    is_24h          BOOLEAN  NOT NULL DEFAULT FALSE,
    is_closed       BOOLEAN  NOT NULL DEFAULT FALSE,
    CONSTRAINT unique_working_hours UNIQUE (day_of_week),
    CONSTRAINT check_hours_not_both CHECK (NOT (is_24h AND is_closed)),
    CONSTRAINT check_hours_times CHECK (
        (is_24h OR is_closed) AND opens_at IS NULL AND closes_at IS NULL
        OR
        (NOT is_24h AND NOT is_closed AND opens_at IS NOT NULL AND closes_at IS NOT NULL)
    )
);
COMMENT ON COLUMN working_hours.hours_id IS 'Surrogate primary key for the hours row';
COMMENT ON COLUMN working_hours.day_of_week IS 'ISO-8601 weekday: 1=Monday ... 7=Sunday';
COMMENT ON COLUMN working_hours.opens_at IS 'Opening time; NULL when is_24h or is_closed';
COMMENT ON COLUMN working_hours.closes_at IS 'Closing time; NULL when is_24h or is_closed';
COMMENT ON COLUMN working_hours.is_24h IS 'TRUE if open around the clock on this day';
COMMENT ON COLUMN working_hours.is_closed IS 'TRUE if fully closed on this day';
COMMENT ON CONSTRAINT unique_working_hours ON working_hours IS 'Times required only for bounded days';
COMMENT ON CONSTRAINT check_hours_not_both ON working_hours IS 'A day cannot be both 24h and closed';
COMMENT ON CONSTRAINT check_hours_times ON working_hours IS 'Mixed time configuration';

-- reservations
CREATE TABLE IF NOT EXISTS reservations (
    id                SERIAL PRIMARY KEY,
    space_id          INTEGER         REFERENCES spaces(space_id),
    customer_name     VARCHAR(100)    NOT NULL,
    license_plate     VARCHAR(20)     NOT NULL,
    start_datetime    TIMESTAMP       NOT NULL,
    end_datetime      TIMESTAMP       NOT NULL,
    total_cost        NUMERIC(10, 2),
    created_at        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT valid_period CHECK (start_datetime < end_datetime)
);

-- SEED DATA
-- pricing
INSERT INTO pricing (price_type, amount, currency, description) VALUES
    ('hourly',      3.00, 'EUR', 'Standard hourly rate for all space types'),
    ('daily_max',  25.00, 'EUR', 'Maximum charge per calendar day'),
    ('monthly',   200.00, 'EUR', 'Monthly subscription — unlimited in/out access'),
    ('ev_charging', 0.30, 'EUR', 'EV charging rate per kWh')
;


-- working_hours
INSERT INTO working_hours (day_of_week, is_24h) VALUES
    ('Monday',    TRUE),
    ('Tuesday',   TRUE),
    ('Wednesday', TRUE),
    ('Thursday',  TRUE),
    ('Friday',    TRUE),
    ('Saturday',  TRUE),
    ('Sunday',    TRUE)
;


DO $$
DECLARE i INT;
BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B1', 'H' || LPAD(i::TEXT, 2, '0'), 'ACCESSIBLE')
        ;
    END LOOP;

    FOR i IN 1..10 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B1', 'EV' || LPAD(i::TEXT, 2, '0'), 'EV')
        ;
    END LOOP;

    FOR i IN 1..30 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B1', 'S' || LPAD(i::TEXT, 2, '0'), 'STANDARD')
        ;
    END LOOP;
END $$;

-- level B2: 20 compact, 30 standard
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 1..20 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B2', 'C' || LPAD(i::TEXT, 2, '0'), 'COMPACT')
        ;
    END LOOP;

    FOR i IN 1..30 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B2', 'S' || LPAD(i::TEXT, 2, '0'), 'STANDARD')
        ;
    END LOOP;
END $$;

-- level B3: 10 EV, 40 standard
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 11..20 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B3', 'EV' || LPAD(i::TEXT, 2, '0'), 'EV')
        ;
    END LOOP;

    FOR i IN 1..40 LOOP
        INSERT INTO spaces (level, space_number, space_type)
        VALUES ('B3', 'S' || LPAD(i::TEXT, 2, '0'), 'STANDARD')
        ;
    END LOOP;
END $$;

COMMIT;
